#ifndef _EXPORTS_H_TLKIT__
#define _EXPORTS_H_TLKIT__

#define TRANTOR_EXPORT
#define TRANTOR_NO_EXPORT

#define TRANTOR_DEPRECATED  __declspec(deprecated)
#define TRANTOR_DEPRECATED_EXPORT  TRANTOR_EXPORT
#define TRANTOR_DEPRECATED_NO_EXPORT TRANTOR_NO_EXPORT

#endif 