# ------------------------------------------------------------------------
# zlib:
# ------------------------------------------------------------------------
add_subdirectory(zlib)
# ------------------------------------------------------------------------
# @end zlib
# ------------------------------------------------------------------------

# ------------------------------------------------------------------------
# jsoncpp:
# ------------------------------------------------------------------------
add_subdirectory(jsoncpp)
# ------------------------------------------------------------------------
# @end jsoncpp
# ------------------------------------------------------------------------

# ------------------------------------------------------------------------
# sqlite3:
# ------------------------------------------------------------------------
add_subdirectory(sqlite)
# ------------------------------------------------------------------------
# @end sqlite3
# ------------------------------------------------------------------------

# ------------------------------------------------------------------------
# brotli:
# ------------------------------------------------------------------------
add_subdirectory(brotli)
# set(BROTLI_LIBRARIES_CORE brotliencstatic brotlidecstatic brotlicommonstatic)
# if(BROTLI_BUILD_STATIC_LIBS)
#     update_cached_list(PA_LINK_LIBRARIES ${BROTLI_LIBRARIES_CORE})
# endif()
# ------------------------------------------------------------------------
# @end brotli
# ------------------------------------------------------------------------

# ------------------------------------------------------------------------
# trantor:
# ------------------------------------------------------------------------
add_subdirectory(trantor)
# ------------------------------------------------------------------------
# @end trantor
# ------------------------------------------------------------------------

# ------------------------------------------------------------------------
# drogon:
# ------------------------------------------------------------------------
add_subdirectory(drogon)
# ------------------------------------------------------------------------
# @end drogon
# ------------------------------------------------------------------------
